#!/system/bin/sh
# AndroidTProxyShell adapter. The service owns process lifecycle; this owns rules.

SCRIPTS_DIR=$(dirname "$0")
. "$SCRIPTS_DIR/lib.sh"
load_config

tproxy_enabled() {
  [ "$proxy_mode" = "redirect" ] || [ "$proxy_mode" = "tproxy" ]
}

tproxy_command() {
  printf '%s' "${tproxy_path:-$sing_box_path/bin/atp}"
}

tproxy_runtime_dir="$runtime_tproxy_dir"

prepare_tproxy_config() {
  [ -f "$user_scripts_path/tproxy.conf" ] || { echo "[Error] 缺少透明代理配置: $user_scripts_path/tproxy.conf" >&2; return 1; }
  mkdir -p "$tproxy_runtime_dir" || return 1
  cp -f "$user_scripts_path/tproxy.conf" "$tproxy_runtime_dir/tproxy.conf" || return 1

  # AndroidTProxyShell auto mode may fall back from TPROXY to REDIRECT. The
  # sing-box inbound is already fixed by proxy_mode, so make this contract
  # explicit in the disposable rule configuration.
  # shellcheck disable=SC1090
  . "$user_scripts_path/tproxy.conf"
  _auto_bypass_apps=""
  [ -f "$auto_bypass_apps_file" ] && _auto_bypass_apps=$(tr '\n' ' ' <"$auto_bypass_apps_file")
  case "${APP_PROXY_MODE:-blacklist}" in
    blacklist)
      _bypass_apps=$(printf '%s %s' "${BYPASS_APPS_LIST:-}" "$_auto_bypass_apps" | tr -s '[:space:]' '\n' | awk 'NF && !seen[$0]++ { printf "%s%s", sep, $0; sep=" " }')
      ;;
    whitelist)
      # AndroidTProxyShell only evaluates PROXY_APPS_LIST in whitelist mode.
      # Keep the source bypass list unchanged and do not add automatic items.
      _bypass_apps=${BYPASS_APPS_LIST:-}
      ;;
    *)
      echo "[Error] APP_PROXY_MODE 必须为 blacklist 或 whitelist" >&2
      return 1
      ;;
  esac
  _escaped_bypass_apps=$(printf '%s' "$_bypass_apps" | sed 's/[\\$`"\\]/\\&/g')
  case "$proxy_mode" in
    tproxy)
      _rule_mode=1
      _dns_mode=${DNS_HIJACK_ENABLE:-1}
      [ "$_dns_mode" = "0" ] || _dns_mode=1
      ;;
    redirect)
      _rule_mode=2
      _dns_mode=${DNS_HIJACK_ENABLE:-1}
      [ "$_dns_mode" = "0" ] || _dns_mode=2
      ;;
  esac
  {
    echo ""
    echo "# Generated by sing-box module; do not edit this runtime copy."
    echo "BYPASS_APPS_LIST=\"$_escaped_bypass_apps\""
    echo "PROXY_MODE=$_rule_mode"
    echo "DNS_HIJACK_ENABLE=$_dns_mode"
  } >>"$tproxy_runtime_dir/tproxy.conf"
}

tproxy_start() {
  tproxy_enabled || return 0
  _tproxy=$(tproxy_command)
  [ -f "$_tproxy" ] || { echo "[Error] 缺少 AndroidTProxyShell: $_tproxy" >&2; return 1; }
  mkdir -p "$run_path" || return 1
  prepare_tproxy_config || return 1
  sh "$_tproxy" -d "$tproxy_runtime_dir" start || return 1
  : >"$tproxy_state_file"
}

tproxy_stop() {
  # Always try cleanup when a previous start recorded state. This also handles
  # users changing proxy_mode before stopping the service.
  if ! tproxy_enabled && [ ! -f "$tproxy_state_file" ]; then
    return 0
  fi
  _tproxy=$(tproxy_command)
  if [ -f "$_tproxy" ]; then
    _tproxy_dir=$user_scripts_path
    [ -f "$tproxy_runtime_dir/tproxy.conf" ] && _tproxy_dir=$tproxy_runtime_dir
    sh "$_tproxy" -d "$_tproxy_dir" stop || return 1
  fi
  rm -f "$tproxy_state_file"
}

case "$1" in
  start) tproxy_start ;;
  stop) tproxy_stop ;;
  *) echo "用法: $0 {start|stop}" >&2; exit 2 ;;
esac
