#!/system/bin/sh
# AndroidTProxyShell adapter. The service owns process lifecycle; this owns rules.

SCRIPTS_DIR=$(dirname "$0")
. "$SCRIPTS_DIR/lib.sh"
load_config

# Magisk/KernelSU/APatch 以 busybox ash standalone 模式执行模块脚本,
# `command ip` 直接命中 busybox ip applet, 而 busybox ip rule 仅支持 table<=1023,
# 会拒绝模块默认表 ID 2025。unset 后子进程 atp 的 sh 不再 standalone,
# command ip 走 PATH 命中 iproute2 (/system/bin/ip)。
unset ASH_STANDALONE 2>/dev/null

tproxy_enabled() {
  [ "$proxy_mode" = "redirect" ] || [ "$proxy_mode" = "tproxy" ]
}

tproxy_command() {
  printf '%s' "${tproxy_path:-$sing_box_path/bin/atp}"
}

tproxy_runtime_dir="$runtime_tproxy_dir"
local_bypass_chain="SB_MODULE_LOCAL_BYPASS"
atp_log_file="$run_path/atp.log"

rotate_atp_logs() {
  mkdir -p "$run_path" || return 1
  mv "$atp_log_file" "$atp_log_file.bak" >/dev/null 2>&1
  : >"$atp_log_file" || return 1
}

redirect_tproxy_output() {
  mkdir -p "$run_path" || return 1
  exec >>"$atp_log_file" 2>&1
}

cleanup_local_bypass_rules() {
  for _cmd in iptables ip6tables; do
    command -v "$_cmd" >/dev/null 2>&1 || continue
    _suffix=""
    [ "$_cmd" = "ip6tables" ] && _suffix=6
    for _table in mangle nat; do
      while "$_cmd" -w 100 -t "$_table" -D "BYPASS_IP$_suffix" -j "$local_bypass_chain" 2>/dev/null; do :; done
      "$_cmd" -w 100 -t "$_table" -F "$local_bypass_chain" 2>/dev/null
      "$_cmd" -w 100 -t "$_table" -X "$local_bypass_chain" 2>/dev/null
    done
  done
}

refresh_local_bypass_family() { # $1=iptables command, $2=table, $3=suffix, $4=IP version
  _cmd=$1
  _table=$2
  _suffix=$3
  _version=$4

  "$_cmd" -w 100 -t "$_table" -N "$local_bypass_chain" 2>/dev/null || return 1
  "$_cmd" -w 100 -t "$_table" -F "$local_bypass_chain" || return 1
  "$_cmd" -w 100 -t "$_table" -I "BYPASS_IP$_suffix" 1 -j "$local_bypass_chain" || return 1

  if [ "$_version" = "4" ]; then
    ip -4 addr show 2>/dev/null | awk '$1 == "inet" && $2 !~ /^127\./ { print $2 }'
  else
    ip -6 addr show 2>/dev/null | awk '$1 == "inet6" && $2 !~ /^(::1|fe80:)/ { print $2 }'
  fi | while IFS= read -r _address; do
    [ -n "$_address" ] || continue
    "$_cmd" -w 100 -t "$_table" -A "$local_bypass_chain" -d "$_address" -p udp ! --dport 53 -j ACCEPT
    "$_cmd" -w 100 -t "$_table" -A "$local_bypass_chain" -d "$_address" ! -p udp -j ACCEPT
  done
}

refresh_local_bypass_rules() {
  [ -f "$tproxy_state_file" ] || return 0
  [ -f "$tproxy_runtime_dir/runtime_tproxy.conf" ] || return 0

  # shellcheck disable=SC1090
  . "$tproxy_runtime_dir/runtime_tproxy.conf"
  case "${USE_TPROXY:-}" in
    1) _table=mangle ;;
    0) _table=nat ;;
    *) return 0 ;;
  esac

  cleanup_local_bypass_rules
  refresh_local_bypass_family iptables "$_table" "" 4 || return 0
  [ "${PROXY_IPV6:-0}" = "1" ] && refresh_local_bypass_family ip6tables "$_table" 6 6
}

prepare_tproxy_config() {
  [ -f "$user_scripts_path/tproxy.conf" ] || { echo "[Error] 缺少透明代理配置: $user_scripts_path/tproxy.conf" >&2; return 1; }
  mkdir -p "$tproxy_runtime_dir" || return 1
  cp -f "$user_scripts_path/tproxy.conf" "$tproxy_runtime_dir/tproxy.conf" || return 1

  # AndroidTProxyShell auto mode may fall back from TPROXY to REDIRECT. The
  # sing-box inbound is already fixed by proxy_mode, so make this contract
  # explicit in the disposable rule configuration.
  # shellcheck disable=SC1090
  . "$user_scripts_path/tproxy.conf"
  _auto_proxy_apps=""
  _auto_bypass_apps=""
  _app_proxy_enable=0
  _app_proxy_mode=${app_proxy_mode:-whitelist}
  [ -f "$auto_proxy_apps_file" ] && _auto_proxy_apps=$(tr '\n' ' ' <"$auto_proxy_apps_file")
  [ -f "$auto_bypass_apps_file" ] && _auto_bypass_apps=$(tr '\n' ' ' <"$auto_bypass_apps_file")
  [ -f "$app_proxy_enabled_file" ] && _app_proxy_enable=$(cat "$app_proxy_enabled_file")
  [ -f "$app_proxy_mode_file" ] && _app_proxy_mode=$(cat "$app_proxy_mode_file")
  case "$_app_proxy_mode" in
    blacklist|whitelist) ;;
    *)
      echo "[Error] app_proxy_mode 必须为 blacklist 或 whitelist" >&2
      return 1
      ;;
  esac
  _escaped_proxy_apps=$(printf '%s' "$_auto_proxy_apps" | sed 's/[\\$`"\\]/\\&/g')
  _escaped_bypass_apps=$(printf '%s' "$_auto_bypass_apps" | sed 's/[\\$`"\\]/\\&/g')
  case "$_app_proxy_mode" in
    blacklist) _escaped_proxy_apps="" ;;
    whitelist) _escaped_bypass_apps="" ;;
  esac
  case "$proxy_mode" in
    tproxy)
      _rule_mode=1
      _dns_mode=${DNS_HIJACK_ENABLE:-1}
      [ "$_dns_mode" = "0" ] || _dns_mode=1
      ;;
    redirect)
      _rule_mode=2
      _dns_mode=${DNS_HIJACK_ENABLE:-1}
      [ "$_dns_mode" = "0" ] || _dns_mode=2
      ;;
  esac
  {
    echo ""
    echo "# Generated by sing-box module; do not edit this runtime copy."
    # atp v26.06.07 的 log() 在 load_config 后半段才初始化 LOG_TIMESTAMP,
    # 提前定义避免 source 阶段 `[ "$LOG_TIMESTAMP" -eq 1 ]` 报 bad number。
    echo "LOG_TIMESTAMP=1"
    echo "APP_PROXY_ENABLE=$_app_proxy_enable"
    echo "APP_PROXY_MODE=\"$_app_proxy_mode\""
    echo "PROXY_APPS_LIST=\"$_escaped_proxy_apps\""
    echo "BYPASS_APPS_LIST=\"$_escaped_bypass_apps\""
    echo "PROXY_MODE=$_rule_mode"
    echo "DNS_HIJACK_ENABLE=$_dns_mode"
  } >>"$tproxy_runtime_dir/tproxy.conf"
}

tproxy_start() {
  # Remove a chain left behind by an interrupted stop before applying rules.
  cleanup_local_bypass_rules
  tproxy_enabled || return 0
  _tproxy=$(tproxy_command)
  [ -f "$_tproxy" ] || { echo "[Error] 缺少 AndroidTProxyShell: $_tproxy" >&2; return 1; }
  prepare_tproxy_config || return 1
  sh "$_tproxy" -d "$tproxy_runtime_dir" start || return 1
  : >"$tproxy_state_file"
  refresh_local_bypass_rules
}

tproxy_stop() {
  cleanup_local_bypass_rules
  # Always try cleanup when a previous start recorded state. This also handles
  # users changing proxy_mode before stopping the service.
  if ! tproxy_enabled && [ ! -f "$tproxy_state_file" ]; then
    return 0
  fi
  _tproxy=$(tproxy_command)
  if [ -f "$_tproxy" ]; then
    _tproxy_dir=$user_scripts_path
    [ -f "$tproxy_runtime_dir/tproxy.conf" ] && _tproxy_dir=$tproxy_runtime_dir
    sh "$_tproxy" -d "$_tproxy_dir" stop || return 1
  fi
  rm -f "$tproxy_state_file"
}

case "$1" in
  start)
    rotate_atp_logs || exit 1
    redirect_tproxy_output || exit 1
    tproxy_start
    ;;
  stop)
    redirect_tproxy_output || exit 1
    tproxy_stop
    ;;
  refresh-local-bypass)
    redirect_tproxy_output || exit 1
    refresh_local_bypass_rules
    ;;
  cleanup)
    redirect_tproxy_output || exit 1
    cleanup_local_bypass_rules
    ;;
  *) echo "用法: $0 {start|stop|refresh-local-bypass|cleanup}" >&2; exit 2 ;;
esac
